name: GitVersioniser
on:
  workflow_run:
    workflows: ["Linters"]
    branches: [main]
    types:
      - completed
jobs:
  repository_versioning:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Repository Versioning via GitVersioniser
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
        with:
          path: target_repository
          fetch-depth: 0
      - name: Running GitVersioniser
        id: gitversioniser
        uses: luzkan/GitVersioniser@main
        with:
          # ===========================
          #        Credentials
          # ---------------------------
          # Versioniser Git Credentials
          # ----
          versioniser_username: "GitVersioniser"
          versioniser_email: "luzkan.gitversioniser@github.com"

          # ===========================
          #          Patterns
          # ---------------------------
          # Increment Tags
          # ----
          commit_pattern_increment_tags: "HashtagExplicit"
          # ---------------------------
          # Change Tags
          # ----
          commit_pattern_change_tags: "All"
  
          # ===========================
          #          Routines
          # ---------------------------
          # Versioning
          # ----
          routine_version: "VersionTagInCommitsTillLastGitVersioniserCommit"
          # ---------------------------
          # Contributing
          # ----
          routine_should_contribute: "IfNewVersionIsBuildOrHigher"
          routine_commiting: "PushOriginAmend"
          # ---------------------------
          # Commit Message
          # ----
          routine_commit_message_describe_changes: "WithEmoji"
          routine_commit_message_format_version_tag: "FullButOnlyDigits"
          routine_commit_message_place_version_tag: "Prefix"
          routine_commit_message_summarize_changes: "WithEmojiCounted"
          # ---------------------------
          # Tagging
          # ----
          routine_tagging: "Regular"
          routine_prefix_tag_with_v: "Never"
          # ---------------------------
          # Changelog Handling
          # -----
          routine_changelog: "CommitChangeTags"
          # ---------------------------
          # File Versioning
          # ----
          routine_file_updater: "VersioniseFiles"
          versioned_files: "package.json"
